name: 'Test actions'

on:
  push:
    branches: [ dev ]
    paths:
      - 'backend/**/*'
      - 'frontend/**/*'
  workflow_dispatch:
    branches: [ dev ]

jobs:
  conditional_step:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
#        fetch-depth: 0

    - shell: pwsh
      id: check_file_changed
      run: |
        $diff = git diff --name-only HEAD^ HEAD

        $SourceDiff = $diff | Where-Object { $_ -match '^backend/' }
        $HasDiff = $SourceDiff.Length -gt 0

        Write-Host "::set-output name=docs_changed::$HasDiff"

    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      if: steps.check_file_changed.outputs.docs_changed == 'True'
      run: echo publish docs
